### PR TITLE
cleanup code

### PR DESCRIPTION
**Pull request by valkyrienyanko**

### CODE REVIEW

**Comment by Kiryonn** [comment]
Bruh why did you put space everywhere and called it "Clean up". That's the opposite of it.
Also i'm not sure global usings are great. It makes team work harder since only people who looked everywhere in the code would know it was already imported. I personally would prefer having them in each file to make my debug easier. There's also the compatibility issue since it's a C#10 feature, meaning anything bellow that won't work (remember Unity still uses C#9). Lastly, as far as i am aware, nothing changes once compiled.

At the end of the day, it's up to the repo owner to decide

**Comment by valkyrienyanko** [comment]
Just ignore the PR, all of these changes can be done in a few clicks in VS2022. As side note this PR is one year old, I don't use global usings or expression lines anymore.

**Comment by eumario** [comment]
@valkyrienyanko 
> Just ignore the PR, all of these changes can be done in a few clicks in VS2022. As side note this PR is one year old, I don't use global usings or expression lines anymore.

No worries, I figured that is what it was about.  I use Rider, and it tends to provide these suggestions every time I open the project, but for comparability, I kept them to be built with the .NET 4.7 Framework for Godot 3.5/3.6.

@Kiryonn 
> Bruh why did you put space everywhere and called it "Clean up". That's the opposite of it. Also i'm not sure global usings are great. It makes team work harder since only people who looked everywhere in the code would know it was already imported. I personally would prefer having them in each file to make my debug easier. There's also the compatibility issue since it's a C#10 feature, meaning anything bellow that won't work (remember Unity still uses C#9). Lastly, as far as i am aware, nothing changes once compiled.
> 
> At the end of the day, it's up to the repo owner to decide

I'm not sure why you felt a need to post a comment on this PR, as the details within it weren't really something that required the response that you provided.  Everyone has their own way of formatting code, and their own ways doing things.  The only time it should be commented on, is if there's a preferred coding style outlined by the Author, or maintainers of a project.  And I don't know why Unity would be of perspective when this is a Godot Project, and has no effect on Unity itself, but that would only matter if your compiling it yourself, with the Godot engine.

**Comment by valkyrienyanko** [comment]
In hindsight, I should have contacted you before creating a PR with 100% personal preference changes or rather focused on adding a feature, so I apologize for this. Going forward I've made the promise to myself not to create PRs like this and rather only focus on PRs that add new feature(s).

**Comment by Kiryonn** [comment]
> I'm not sure why you felt a need to post a comment on this PR

As someone who values performance a lot and have to deal with people who don't understand how to use a try catch, parse a data 4 times in a row,... on a daily basis, I'm genuinely offended by those spaces.

One of my colleagues don't understand what creating functions and multiple files means, so i ended up looking at a 10k+ lines script for a form. All spaces. And what do you know, changing them to tabs reduced the file size by 33%.

As I said, once compiled, nothing changes. But what if I told you that vscode was strungling suggesting changes before i did that, and that it was faster afterwards ? Just by changing those spaces to tabs.
That's quite easy to understand why that is.

Now imagine if it was also applied to large data files such as jsons. (Before compressing them into one line)

**Pull request closed without merging**
